services:
  mysql:
    container_name: mysql-container
    image: mysql:8.0.29
    ports:
    - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root-password
      - MYSQL_USER=username
      - MYSQL_PASSWORD=user-password
    networks:
      - mysql-phpmyadmin

  phpmyadmin:
    container_name: phpmyadmin-container
    image: phpmyadmin:latest
    ports:
    - 8080:80
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mysql-container
      - PMA_PORT=3306
    depends_on:
      - mysql
    networks:
      - mysql-phpmyadmin

networks:
  mysql-phpmyadmin:
    name: mysql-phpmyadmin